version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.18.0

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Start container and run tests
          command: docker-compose -f docker-compose-test.yml up --exit-code-from sut sut | tee ${TEST_RESULTS}/test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results